Added functionality to re-send the init packet until the ground checksum is verified
svn path=/; revision=4715

diff --git a/Systems/scripts/sendSQL b/Systems/scripts/sendSQL
--- a/Systems/scripts/sendSQL
+++ b/Systems/scripts/sendSQL
@@ -1,4 +1,4 @@
-#!/bin/csh
+#!/bin/bash
 #
 #  This script will recreate the database on the ground
 #    so that inserts sent from the plane will be successful
@@ -8,9 +8,68 @@
 #    Called by Nimbus
 #
 
-cd /tmp/xmit
+#GLOBALS
+filename=`basename $1 .gz`
+timer=20 #seconds to wait between retries
+logNot="logger -t sendGroundInitScript -s -p local1.notice"
+logErr="logger -t sendGroundInitScript -s -p local1.err"
+statusFile=${XMIT_DIR}/noconn
+last_compare=0
 
+export PGHOST=eol-rt-data.guest.ucar.edu
+export PGDATABASE=$PGGRND
+
+function compareChecksum {
+	groundCS=$(psql -t -c "SELECT value from global_attributes where key='checksum'")
+	onboardCS=$(psql -h localhost real-time -t -c "SELECT value from global_attributes where key='checksum'")
+
+	if [ "$onboardCS" = "$groundCS" ]; then
+		last_compare=1
+	else
+		last_compare=0
+	fi
+}
+
+
+#MAIN SCRIPT
+cd $XMIT_DIR #/tmp/xmit
 gunzip $1
-set filename=`basename $1 .gz`
+touch $statusFile #exists only if checksums are not verified
 
-sed 1,1d $filename | psql -h eol-rt-data.guest.ucar.edu -d $PGGRND
+while [ 1 ]; do 
+
+	compareChecksum
+	if [ $last_compare -eq 1 ]; then
+		$logNot "nimbus checksums match."
+		rm -f $statusFile 
+		exit 0
+
+	else
+		$logNot "nimbus checksum mismatch, sending packet."
+		sed 1,1d $filename | psql #send packet
+		stat=$?
+		
+		if [ $stat -eq 0 ]; then #psql connected to ground DB
+			$logNot "ground db connection sucessful."
+		
+		elif [ $stat -eq 1 ]; then #psql fatal error
+			$logErr "FATAL: psql general error."
+			exit 1
+		
+		elif [ $stat -eq 2 ]; then #db connection error
+			$logNot "psql error connecting to $PGHOST, retry again in $timer seconds."
+		
+		elif [ $stat -eq 3 ]; then #sql script error
+			$logErr "FATAL: sqlscript error."
+			exit 1
+		
+		else
+			$logErr "FATAL: unknown error."
+			exit 1
+		
+		fi # if [ $stat -eq 0 ]
+
+	fi # if [ $(compareChecksum) ]
+	sleep $timer
+
+done # while [ 1 ]
